services:
    tournament_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - postgres
    postgres:
        image: postgres:16
        volumes:
            - ./tmp/postgres/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: tournament_test
            POSTGRES_PASSWORD: tournament_test
            POSTGRES_DB: tournament_test
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
